### PR TITLE
Add associative array cartesian products

### PR DESCRIPTION
**Pull request by chx**
This is a fascinating library to calculate cartesian products without recursion and without keeping the whole set in memory. May I ask for associative array support? If this is not desired, could you at least please consider splitting off the init function so I can add my subclass without copying the whole constructor? Thanks.

### CODE REVIEW

**Comment by Hywan** [comment]
@chx ping :smile:?

**Comment by chx** [comment]
Sorry! I will do this weekend.

**Comment by Hywan** [comment]
No hurry :-). It was a simple ping ;-).

**Comment by chx** [comment]
Closing in favor of #23

**Pull request closed without merging**
