### PR TITLE
Add round() function to Arithmetic

### PR DESCRIPTION
**Pull request by zackkatz**
Allow rounding values with the ability to also pass levels of precision

### CODE REVIEW

**Comment by Hywan** [comment]
Hello,

Thanks for the PR! That's a great idea. Why do you have a commit from @mgratch here? Is your `master` up to date?

**Comment by zackkatz** [comment]
@Hywan I'm just bad with Git. It was up to date; [you can see only two lines changed](https://github.com/hoaproject/Math/pull/46/files).

**Comment by Hywan** [comment]
Fixed by https://github.com/hoaproject/Math/commit/8a5cd7d6b3e41afb4f5e429544214b9199641533! Thanks!

**Comment by Hywan** [comment]
Welcome on board, http://hoa-project.net/En/Community.html#Contributors 🎉 ❤️!

**Pull request closed without merging**
