### PR TITLE
support #variable declared in grammar

### PR DESCRIPTION
**Pull request by esion**
_following advices from @jubianchi_

### CODE REVIEW

**Comment by Hywan** [comment]
Hello :-),

Thanks for the PR! However, what is the goal of this PR? Can you provide at least an example, or tests?

**Comment by jubianchi** [comment]
@Hywan we have a use case where we have to parse expression like the following:

```
(nb_something * 2) / 12
```

In the previous expression, `nb_something` is a business data which is computed by one of our software (not the same as the one building expression). We could have used constant but they have to be uppercase.

Moreover, the semantic of constants does not really fit our use case : we don't know the value of `nb_something` in advance and it can change from one parsing to the other.

The actual proposed patch is a bit incomplete though: when we call `addVariable` we have to set a static value for it.

I proposed @esion two alternative solutions:

* when calling `addVariable`we could provide a `callable` so that the value is computed as late as possible or
* we could provide a global variable handler (again as a `callable`) to resolve variables. Each time the visitor finds a variable it calls this handle to get a value.

**Comment by Hywan** [comment]
You didn't explain what this patch does. What do you want to achieve? Lazy variable evaluation?

**Comment by jubianchi** [comment]
@Hywan this patch simply handles variables: this was not the case before. They were described in the grammar but the visitor just ignored them producing errors.

**Comment by Hywan** [comment]
Indeed. The grammar recognizes them but the visitor has not special computation for them. How did we miss that…

Ok, so, yes, having the ability to define a variable value as a closure is also a good thing. See [`Hoa\Ruler`](http://central.hoa-project.net/Resource/Library/Ruler) which has a similar implementation (in the context).

**Comment by Hywan** [comment]
Let me know when the PR is ready for a review!

**Comment by jubianchi** [comment]
> having the ability to define a variable value as a closure is also a good thing

@Hywan @esion I think this is the most simple thing to implement : `addVariable` would take a `callable`/`xcallable` as its second argument.

But I think it could be interesting to also add a global variable handler which would, by default, just throw an exception when a variable is requested.

If the user defines a custom global handler, the later will be called if there is no variable callable added through `addVariable`

Thoughts ?

**Comment by Hywan** [comment]
@jubianchi Please, could you provide an example? I don't get the “global variable handler”.

**Comment by jubianchi** [comment]
better: a pr ;)

**Comment by jubianchi** [comment]
> How did we miss that…

@Hywan the test on the visitor seems wrong: because of [this block](https://github.com/hoaproject/Math/blob/master/Test/Unit/Visitor/Arithmetic.php#L86-L88) we never execute any assertion. The generated expression produces a parser error.

**Comment by Hywan** [comment]
@jubianchi No. The grammar we use for testing is another one, based on the “official one”. Because we cannot generate variables with no value and expect PHP to evaluate them correctly too (we compare results from `Hoa\Math` and PHP eveluations).

**Comment by jubianchi** [comment]
@Hywan I know that but none of the generated expression passes they **all** produce parse errors

**Comment by jubianchi** [comment]
with parse error I meant the expressions are not parseable by the library (php is not the problem here)

**Comment by Hywan** [comment]
No, they don't produce parse errror. I don't understand… Can you provide an example please?

**Comment by jubianchi** [comment]
@Hywan just remove the `try`/`catch` i highlighted and see by yourself : on the master, the test suite produces about 60 assertions with something like 30K generated expression. There is a problem.

**Comment by Hywan** [comment]
@jubianchi Please, open an issue for that. Else I won't remember… I don't have time right now for that :-).

**Comment by jubianchi** [comment]
@Hywan ok good. I'm trying to find why this happens because it should not. Once I have enough clues i'll open an issue.

**Comment by Hywan** [comment]
@jubianchi Thanks for your time!

**Comment by Hywan** [comment]
@esion You deserve a contribution note. I will add you in the contributor list but not today, tomorrow or tonight. Cheers!

**Comment by esion** [comment]
thank you @Hywan, but I've almost done nothing except using Hoa/Math :)

**Comment by Hywan** [comment]
@jubianchi Did you re-use some code from @esion :-)?

**Pull request closed without merging**
