### PR TITLE
Validate with float 0.0 before throwing exception

### PR DESCRIPTION
**Pull request by mgratch**
This is exactly the same as my previous PR #36 just a few lines down.  Let me know if you need me to do anything else with this.  Thanks!

### CODE REVIEW

**Comment by Hywan** [comment]
Hi :-),

Sorry for the late reply, we were all in holidays or very busy. Please, can you add a test case like we did in https://github.com/hoaproject/Math/pull/36?

**Comment by Hywan** [comment]
ping? Would you like us to write the test cases?

**Comment by mgratch** [comment]
Add testcase [b0ce818](https://github.com/hoaproject/Math/pull/43/commits/b0ce8184aeacfac5d0332fcd766ba2af7280d01d)  Sorry for the delay!  Thanks!

**Comment by Hywan** [comment]
No worry for the delay :-).

**Comment by Hywan** [comment]
In order to ameliorate our contribution process, could you answer the following question please? Was it helpful to write the test case by yourself (did you learn something) or was it something annoying you would likely see done by us?

**Comment by mgratch** [comment]
Ivan,

I appreciate learning to do it.  I am used to working with phpunit for WP
unit testing so this is nice exercise and broadens my base.

Thanks for everything you guys do!
Marc

**Comment by Hywan** [comment]
Thanks for your feedback. Really appreciate it!

**Pull request merged**
